-- MySQL Script generated by MySQL Workbench
-- Sat Feb 23 02:56:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laundry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laundry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laundry` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `laundry` ;

-- -----------------------------------------------------
-- Table `laundry`.`process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laundry`.`process` (
  `idprocess` INT NOT NULL AUTO_INCREMENT,
  `added_on` DATE NULL,
  `status` VARCHAR(30) NULL,
  PRIMARY KEY (`idprocess`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laundry`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laundry`.`settings` (
  `idsettings` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `companyAddress` VARCHAR(45) NOT NULL,
  `companyTelephone` VARCHAR(15) NOT NULL,
  `companyEmail` VARCHAR(45) NULL,
  `license` DATE NOT NULL,
  `license_fee` DECIMAL NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idsettings`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laundry`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laundry`.`services` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(45) NOT NULL,
  `idsettings` INT NOT NULL,
  PRIMARY KEY (`idservice`),
  INDEX `fk_services_settings_idx` (`idsettings` ASC),
  CONSTRAINT `fk_services_settings`
    FOREIGN KEY (`idsettings`)
    REFERENCES `laundry`.`settings` (`idsettings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laundry`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laundry`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `usertype` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userimage` VARCHAR(45) NULL,
  `idsettings` INT NOT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `fk_users_settings1_idx` (`idsettings` ASC),
  CONSTRAINT `fk_users_settings1`
    FOREIGN KEY (`idsettings`)
    REFERENCES `laundry`.`settings` (`idsettings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
